# Generated by Django 4.1.5 on 2023-03-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="shop/category-icon",
                        verbose_name="عکس دسته بندی",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="نام دسته بندی",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "دسته بندی ها",
                "ordering": ("-created",),
            },
        ),
    ]
