# Generated by Django 4.1.5 on 2023-03-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_test_delete_categories"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
