# Generated by Django 4.1.5 on 2023-03-28 16:49

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="shop/category",
                        verbose_name="عکس دسته بندی",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="نام دسته بندی",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "تنظیمات قسمت دسته بندی",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="نام کالا"
                    ),
                ),
                (
                    "enlish_title",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="نام کالا به اینگلیسی",
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True)),
                (
                    "short_discription",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="توضیحات کوتاه"
                    ),
                ),
                (
                    "price",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="قیمت اصلی کالا"
                    ),
                ),
                (
                    "persent_of_price",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="درصد تخفیف"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="نوع"
                    ),
                ),
                (
                    "code",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="شناسه"
                    ),
                ),
                (
                    "grantee",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="گارانتی"
                    ),
                ),
                (
                    "Availablelty",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="تعداد موجودی کالا"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(default=True, verbose_name="ایا موجود است ؟"),
                ),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="توضیحات"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ManyToManyField(
                        blank=True,
                        related_name="products",
                        to="shop.category",
                        verbose_name="دسته بندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "کالا",
                "verbose_name_plural": " کالاها",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Sellers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="نام فروشنده",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="shop/seller_image",
                        verbose_name="عکس فروشنده",
                    ),
                ),
                (
                    "address",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="ادرس فروشنده"
                    ),
                ),
                (
                    "phone",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="شماره تلفن"
                    ),
                ),
                (
                    "discription",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="توضیحات فروشنده"
                    ),
                ),
            ],
            options={
                "verbose_name": "فروشنده",
                "verbose_name_plural": "فروشنده ها",
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="مقدار"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "سایز و وزن",
                "verbose_name_plural": "سایز و وزن",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Sorting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="اسم طبقه بندی:",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "مرتب سازی",
                "verbose_name_plural": "مرتب سازی با",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="نام برچسب"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "بر چسب",
                "verbose_name_plural": "برچسب ها",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Tip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="نکته ها"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "نکته",
                "verbose_name_plural": " نکات",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="shop/image",
                        verbose_name="عکس کالا",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.product",
                        verbose_name="کالا",
                    ),
                ),
            ],
            options={
                "verbose_name": "عکس کالا",
                "verbose_name_plural": " عکس کالاها ",
                "ordering": ("-created",),
            },
        ),
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="shop.sellers",
                verbose_name="فروشنده",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="shop.size",
                verbose_name="سایز و وزن",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sort_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="shop.sorting",
                verbose_name="مرتب سازی با:",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tag",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="shop.tag",
                verbose_name="بر چسب ها",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tips",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="shop.tip", verbose_name="نکات"
            ),
        ),
        migrations.CreateModel(
            name="MetaTip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="نکته"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metatips",
                        to="shop.product",
                        verbose_name="کالا",
                    ),
                ),
            ],
            options={
                "verbose_name": "نکته",
                "verbose_name_plural": " نکات اضافی",
                "ordering": ("-created",),
            },
        ),
    ]
