# Generated by Django 4.1.5 on 2023-03-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_rename_persent_of_price_product_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.SmallIntegerField(
                blank=True, default=0, null=True, verbose_name="درصد تخفیف"
            ),
        ),
    ]
