# Generated by Django 4.1.7 on 2023-04-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_compare"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_not_new",
            field=models.BooleanField(default=False, verbose_name="ایا کارکرده است ؟"),
        ),
        migrations.AddField(
            model_name="product",
            name="new",
            field=models.BooleanField(default=False, verbose_name="ایا کالا نو است ؟"),
        ),
    ]
